### ISSUE TITLE
Page request

### ISSUE THREAD

**Issue by g2rant** [aducad/cloud-game-lister#4]
Any chance you could add this to the user library page (https://support.steampowered.com/kb_article.php?ref=6324-IGHC-5301)? I've never worked on a Chrome extension before and don't have the time to figure it out right now, otherwise I would do it myself and submit a pull request. Looking at some of your commits, it looks like this is the information needed to make it happen:

- URL pattern `"matches": ["*://steamcommunity.com/profiles/*/games/*"]`
- `const rows = document.querySelectorAll('#games_list_rows .gameListRow:not(.cgl-applied)')`
- The appId just has to be extracted from each elements' `id` property, which has a pattern of `"game_*"`, where the appId is in that wildcard.

The whole page looks fairly simple to me, but I could definitely be misunderstanding some things so let me know if you need something more before you can add this. I'd appreciate it!

**Comment by emresandikci** [comment]
@gillegra sorry for the late reply, we are busy nowadays. if I didn't misunderstand you, we can add a support icon to the user library page. But on the link, the topic about Steam’s Remote Downloads feature, so is this link related to your feature request?

**Comment by g2rant** [comment]
No worries about timing. Looking back at that, I'm actually not sure why I included that KB link. Otherwise, yes you are correct that I'm hoping for the support icon to be added to the user library page.

**Comment by emresandikci** [comment]
@gillegra hey again, the requested feature is ready. We published it and it will be on live soon when chrome webstore approve it. Probably in 3 days 🚀
